project_id = "unraveled"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.score]
verify_jwt = false

[functions.trend-analyze]
verify_jwt = false

[functions.alternatives]
verify_jwt = false

[functions.trend-image]
verify_jwt = false
